### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by jokerlsq** [islambarakat99/Multi-Robot-Formation-Control-using-Deep-Reinforcement-Learning#6]
Hello, I urgently need your help, hope this program can run on my computer,
At present, various errors are always reported when python is running, and it cannot be solved. Your guidance is very much needed, thank you

**Comment by jokerlsq** [comment]
I sincerely ask for your help again

**Comment by jokerlsq** [comment]
I don't know how to configure the environment for this project, because tensorflow has undergone relatively large changes, and the version adaptation of various parts such as code and python environment has no way to start. I also don't know from which .py file the program here should start to run, I really need your help urgently. 
help me and save my dying life

**Comment by islambarakat99** [comment]
Hello,
I have noticed those issues and I was working on fixing them from time to time, unfortunately I haven't had so much time to re-solve completely the migration to Tensorflow 2

However, I have been able to solve some problems on this branch **"customized version"** , you can find there some fixes that I will be working on completing them all very soon hopefully

Thanks
